
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://begjbzrzxmbwsrniirao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZ2pienJ6eG1id3NybmlpcmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1OTUzODgsImV4cCI6MjA1NDE3MTM4OH0.M12TudEZqwnImyu1EvQ0Ha-s3fsHafx9ZxWsD8FCc98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function for checking if a table exists
export const checkTableExists = async (tableName: string): Promise<boolean> => {
  try {
    // The query will succeed even if table doesn't exist, so we check the error message
    const { error } = await supabase
      .from(tableName)
      .select('*')
      .limit(0);
    
    // If error code is 42P01, the table doesn't exist
    if (error && error.code === '42P01') {
      console.log(`Table ${tableName} does not exist`);
      return false;
    }
    
    return true;
  } catch (error) {
    console.error(`Error checking if table ${tableName} exists:`, error);
    return false;
  }
};
